### PR TITLE
feat(offer): refinement and implementation of new features

### PR DESCRIPTION
**Pull request by AdrianAlzamoraG**
### What does it do

Describe the technical changes you did.

### Usage

If applicable, include a small code snippet in which you demonstrate how to use the new feature.

### Why is it needed

Describe the issue you are solving.

### Related issue(s)/PR(s)

Add any related issue/pull request here.

### CODE REVIEW

**Comment by AdrianAlzamoraG** [comment]
> @AdrianAlzamoraG Is this ready for review? If it is, request my review.

@dalbitresb12 not yet, I managed to fix that the chekbox list appears but you can only select all of them and not each one. Also when I want to apply filter it doesn't work and now the table loading icon is not shown anymore.

**Comment by dalbitresb12** [comment]
Let's merge this so that I can rewrite the component using `<script setup>` and maybe this will fix most of the bugs. What do you think? @AdrianAlzamoraG

**Comment by AdrianAlzamoraG** [comment]
I agree with your idea @dalbitresb12 you can proceed with the changes.

**Review by dalbitresb12 — APPROVED** [review]
Merging with pending refactor. Thanks, @AdrianAlzamoraG!

**Pull request merged**
